framework: "huggingface"


device: "cuda"
mode: "AutoModelForSeq2SeqLM"
model: 
  name: "google/flan-t5-base"
  
batch_size: 20
skip_special_tokens: true

# Parameters for GenerationConfig
# Please do check the documentation: c.f. https://huggingface.co/docs/transformers/main/en/main_classes/text_generation#transformers.GenerationConfig
params:
  max_new_tokens: 128
  early_stopping: true
  num_beams: 3
  use_cache: true
  do_sample: false
  temperature: 0.0
  top_p: 1.0
  top_k: 50
  num_return_sequences: 1