framework: "openai"

mode: "chat"
batch_size: 20

# API details on "chat" task can be found here: https://platform.openai.com/docs/api-reference/chat
params:  # Below shows the parameters that are passed to the API call directly
  model: "gpt-4"
  max_tokens: 128
  temperature: 1.0
  top_p: 1
  n: 1
  stream: false
  stop: null
  presence_penalty: 0
  frequency_penalty: 0
  logit_bias: {}
